account/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from . import views

app_name = 'account'

urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view() , name='logout'),
    path('login/', views.user_login, name='login'),
    path('search/', views.search_for_room, name='search'),
    path('room/<pk>', views.userDetail, name='user_detail')
]

leadrboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from account import views


urlpatterns = [
    path('', views.user_register, name='home'),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('room/', include('room.urls', namespace='room')),
]

room/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'room'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('manage/', login_required(views.allPlayer.as_view(), login_url='home'), name='manage'),
    path('manage/<pk>/', login_required(views.SinglePlayer.as_view()), name='player_detail'),
    path('dashboard/', views.Dashboard, name='dashboard'),
    path('manage/delete/<pk>', login_required(views.DeletePlayer.as_view(), login_url='home'), name='delete_player'),
    path('manage/reset/<pk>', views.resetPlayer, name='reset_player')
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Sniglet:800" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand light navbar-title" href="{% url 'home' %}">LeadrBoards</a>
        <ul class="navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li class="nav-item"><a href="{% url 'room:add' %}" class="nav-link">ADD</a></li>
            <li class="nav-item"><a href="{% url 'room:manage'%}" class="nav-link">MANAGE</a></li>
            <li class="nav-item"><a href="{% url 'account:logout' %}" class="nav-link" style="color:red">LOGOUT</a></li>
            <li class="nav-item">

              <form class="form-inline" action="{% url 'account:search' %}" method="GET">
                <div class="input-group mb-3">
                  <input name="search" type="text" class="form-control" placeholder="SEARCH FOR ROOMS" value={{request.GET.search}}>
                    <div class="input-group-append">
                      <button class="btn btn-dark" type="submit">SEARCH</button>
                    </div>
                  </div>
                </form>
            </li
          </ul>

          {% else %}
        </ul>
            <form method="post" action="{% url 'account:login' %}" class="form-inline">
              {% csrf_token %}
              <div class="form-row">
                <div class="input-group mb-2 mr-sm-2">
                  <input class="form-control" type="text" name="username" placeholder="Room Name">
                </div>
                <div class="input-group mb-2 mr-sm-2">
                  <input class="form-control" type="password" name="password" placeholder="Password">
                </div>
                <div class="input-group mb-2 mr-sm-2">
                  <input type="submit" name="" value="LOGIN" class="btn btn-dark">
                </div>
              </div>
            </form>
          {% endif %}
      </div>
    </nav>
    <br>
{% block content %}
{% endblock %}
    <footer class="footer fixed-bottom">
      <div class="container fixed-bottom" align="center">
        <span class="text-muted">Created by <a href="https://sid-hant.github.io" target="_blank">Sidhant</a></span>
      </div>
    </footer>

  </body>

    <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-117104169-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-117104169-1');
  </script>

</html>

templates/dashboard.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block title %}LeadrBoard Room: {{user.username}}{% endblock %}
{% block content %}
<div class="container">
  <div class="jumbotron jumbotron-other" align=center>
    <h1 class="label-for-user">{{user.username}}</h1>
  </div>
  <div class="row">
    <div class="col" align="center">
      <h4 class="labels-for-tables">LEADERBOARD</h4>
      <table class="table table-hover">
      <thead class="thead-dark">
       <tr>
         <th scope="col">NAME</th>
         <th scope="col">GP</th>
         <th scope="col">W</th>
         <th scope="col">L</th>
         <th scope="col">D</th>
       </tr>
      </thead>
      <tbody>
        {% for player in players %}
         <tr>
           <td>{{player.name}}</td>
           <td>{{player.games_played}}</td>
           <td>{{player.wins}}</td>
           <td>{{player.loss}}</td>
           <td>{{player.draw}}</td>
         </tr>
        {% endfor %}
      </tbody>
      </table>
    </div>
    <div class="col" align="center">
      <h4 class="labels-for-tables">MATCHES</h4>
      <table class="table table-hover">
      <thead class="thead-dark">
       <tr>
         <th scope="col">PLAYER</th>
         <th scope="col">SCORE</th>
         <th scope="col">-</th>
         <th scope="col">SCORE</th>
         <th scope="col">PLAYER</th>
       </tr>
      </thead>
      <tbody>
        {% for match in matches %}
         <tr>
           <td align="left" valign="left">{{match.p1_name}}</td>
           <td align="center" valign="middle">({{match.p1_score}}</td>
           <td align="center" valign="middle">-</td>
           <td align="center" valign="middle">{{match.p2_score}})</td>
           <td align="right" valign="right">{{match.p2_name}}</td>
         </tr>
        {% endfor %}
      </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}

templates/error.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block title %}LeadrBoards Error{% endblock %}
{% block content %}
<div class="container">
  <div class="jumbotron" align ="center">
    <h1>ERROR PAGE NOT FOUND</h1>
  </div>
</div>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block title %}LeadrBoards{% endblock %}
{% block content %}
<div class="container">
      {% if user.is_authenticated %}

      {% else %}
      <div class="row">
        <div class="col-8">
          <div class="jumbotron" align="center">
            <h1 class="header-title">LeadrBoards</h1>
            <h3 id='search-title'>SEARCH ROOMS</h3>
            <form class="form" action="{% url 'account:search' %}" method="GET">
                <input name="search" class="form-control" type="search" placeholder="SEARCH FOR ROOMS" aria-label="Search" value={{request.GET.search}}>
                <br>
                <button class="btn btn-dark btn-lg btn-block" type="submit">SEARCH</button>
            </form>
          </div>
        </div>
        <div class="col-4">
      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          {% bootstrap_form user_form %}
        </div>
        <div class="form-group">
          <input type="submit" value="REGISTER" class="btn btn-dark btn-lg btn-block">
        </div>
      </form>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

templates/manage.html
{% extends 'base.html' %}
{% block title %}LeadrBoard Manage Players{% endblock %}
{% block content %}
<div class="container">
  <h4 class="labels-for-tables" align="center">ALL PLAYERS</h4>
  {% for player in players %}
    <div class="jumbotron jumbotron-other" align="center">
      <a style="color:black" href="{{ player.id }}"><h1 >{{player.name}}</h1></a>
    </div>
  {% endfor %}
</div>
{% endblock %}

templates/player_detail.html
{% extends "base.html" %}
{% block title %}LeadrBoards: {{player.name}}{% endblock %}
{% block content %}

<div class="container">
  <div class="jumbotron jumbotron-other" align=center>
    <h1 class="label-for-user">{{player.name}}</h1>
    <p>GAMES PLAYED: {{player.games_played}}</p>
    <p>{{player.wins}}-{{player.loss}}-{{player.draw}} (W-L-D)</p>
    <div class="row">
      <div class="col">
        <a href="{% url 'room:reset_player' pk=player.id%}"><button type="submit" class="btn btn-warning">RESET STATS</button></a>
      </div>
      <div class="col">
        <form action="{% url 'room:delete_player' pk=player.id%}" method="POST">
          {% csrf_token %}
          <button class="btn btn-danger" type="submit">DELETE PLAYER</button>
        </form>
      </div>
    </div>
  </div>
  <div class="container" align="center">


  </div>
</div>
{% endblock %}

templates/search.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block title %}LeadrBoards Search{% endblock %}
{% block content %}
<div class="container">
  <form class="form" action="{% url 'account:search' %}" method="GET">
    <div class="input-group mb-3">
      <input name="search" type="text" class="form-control" placeholder="SEARCH FOR ROOMS" value={{request.GET.search}}>
        <div class="input-group-append">
          <button class="btn btn-dark"  type="submit">SEARCH</button>
        </div>
      </div>
    </form>
    <br>
        {% if rooms %}
          {% for room in rooms %}
            <a href={% url 'account:user_detail' pk=room.id %} style="color:black">
              <div class="jumbotron jumbotron-other" align="center">
                <h1 class="label-for-user">{{room.username}}</h1>
              </div>
            <a>
            <br>
          {% endfor %}
        {% endif %}
</div>
{% endblock %}

templates/setting.html
{% extends 'base.html' %}
{% block title %}LeadrBoard Add{% endblock %}
{% load bootstrap3 %}
{% block content %}
<div class="container">
  <div class="container">
  <div class="row">
    <div class="col">
      <h4 class="labels-for-tables" align="center">ADD MATCH</h4>
      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          {% bootstrap_form match_form %}
        </div>
        <div class="form-group">
          <input type="submit" value="ADD MATCH" class="btn btn-dark btn-lg btn-block">
        </div>
      </form>
    </div>
    <div class="col">
      <h4 class="labels-for-tables" align="center">ADD PLAYER</h4>
      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
          {% bootstrap_form player_form %}
        </div>
        <div class="form-group">
          <input type="submit" value="ADD PLAYER" class="btn btn-dark btn-lg btn-block">
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/user_detail.html
{% extends "base.html" %}
{% block title %}LeadrBoard Room: {{name}}{% endblock %}
{% load bootstrap3 %}
{% block content %}
<div class="container">
  <div class="jumbotron jumbotron-other" align=center>
    <h1 class="label-for-user">{{name}}</h1>
  </div>
  <div class="row">
    <div class="col" align="center">
      <h4 class="labels-for-tables">LEADERBOARD</h4>
      <table class="table table-hover">
      <thead class="thead-dark">
       <tr>
         <th scope="col">NAME</th>
         <th scope="col">GP</th>
         <th scope="col">W</th>
         <th scope="col">L</th>
         <th scope="col">D</th>
       </tr>
      </thead>
      <tbody>
        {% for player in players %}
         <tr>
           <td>{{player.name}}</td>
           <td>{{player.games_played}}</td>
           <td>{{player.wins}}</td>
           <td>{{player.loss}}</td>
           <td>{{player.draw}}</td>
         </tr>
        {% endfor %}
      </tbody>
      </table>
    </div>
    <div class="col" align="center">
      <h4 class="labels-for-tables">MATCHES</h4>
      <table class="table table-hover">
      <thead class="thead-dark">
       <tr>
         <th scope="col">PLAYER</th>
         <th scope="col">SCORE</th>
         <th scope="col">-</th>
         <th scope="col">SCORE</th>
         <th scope="col">PLAYER</th>
       </tr>
      </thead>
      <tbody>
        {% for match in matches %}
         <tr>
           <td align="left" valign="left">{{match.p1_name}}</td>
           <td align="center" valign="middle">({{match.p1_score}}</td>
           <td align="center" valign="middle">-</td>
           <td align="center" valign="middle">{{match.p2_score}})</td>
           <td align="right" valign="right">{{match.p2_name}}</td>
         </tr>
        {% endfor %}
      </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}